logging:
  level:
    ROOT: INFO
    com.javaak.examples.apigateway: DEBUG

spring:
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: 1 # report 100% of traces
#  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
#    base-url: http://localhost:9411
#    enabled: false

server:
  port: 8089
